name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      # https://speaktosteve.github.io/managing-environment-variables-in-nextjs-azure-static-web-apps
      - name: Generate Env File
        run: |
          echo 'VITE_APPINSIGHTS_CONNECTION_STRING=${{ secrets.VITE_APPINSIGHTS_CONNECTION_STRING }}' > .env
          echo 'VITE_AZURE_AI_API_URL=${{ vars.VITE_AZURE_AI_API_URL }}' >> .env
          echo 'VITE_AZURE_AI_SCOPE=${{ vars.VITE_AZURE_AI_SCOPE }}' >> .env
          cat .env
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PURPLE_ROCK_04366A21E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          # Build configuration for Vite + React
          app_location: "/" # App source code path (where package.json is)
          output_location: "/dist" # Vite build output
          # Remove or set skip_app_build to false so Azure builds the app
          skip_app_build: false
          skip_api_build: true
          api_location: "" # Api source code path - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PURPLE_ROCK_04366A21E }}
          action: "close"
